[project]
name = "to-tool-manager"
version = "0.3.4"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Conectar Wali SAS", email = "conectarwalisas@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10.2",
    "ornator",
    "pydantic-ai>=2.10.0",
    "pydantic-ai-harness>=0.7.0",
    "pydantic-ai-skills>=1.2.0",
    "subagents-pydantic-ai>=0.2.10",
]

[project.scripts]
to-tool-manager = "to_tool_manager:main"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fastapi[standard]>=0.139.2",
    "sqlmodel>=0.0.39",
    "pydantic-ai-slim[groq]>=2.10.0",
    "pytest>=9.1.1",
    "httpx>=0.28.1",
]
